//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int resourceId { get; set; }
        public string resourceName { get; set; }
        public string resourceLink { get; set; }
        public string description { get; set; }
        public int proficiencyId { get; set; }
    
        public virtual ProficiencyLevel ProficiencyLevel { get; set; }
    }
}
