//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentResponses = new HashSet<StudentResponse>();
        }
    
        public int studentId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string universityName { get; set; }
        public string email { get; set; }
        public int proficiencyId { get; set; }
        public string password { get; set; }
    
        public virtual ProficiencyLevel ProficiencyLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentResponse> StudentResponses { get; set; }
    }
}
